auctions/urls.py
from django.urls import path

from . import views

app_name = "auctions"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("listing/<int:listing>", views.listing, name="listing"),
    path("bid", views.bid, name="bid"),
    path("comment", views.comment, name="comment"),
    path("watchlist", views.watchlist, name="watchlist"),
    path("addtowatchlist/<int:item_id>", views.add_to_watchlist, name="add_to"),
    path("removefrom/<int:item_id>", views.remove_from, name="remove"),
    path("categories", views.categories, name="categories"),
    path("success", views.success, name="success"),
    path("addListing", views.addListing, name="add_listing"),
    path("user_listings", views.user_listings, name="user_listings"),
    path("close_listing/<int:listing_id>", views.close_listing, name="close_listing"),
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

from . import settings

from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass

class Listing(models.Model):
    CATEGORIES = [
        ('Accessories', 'Accessories'),
        ('Antiques', 'Antiques'),
        ('Clothes', 'Clothes'),
        ('Decoration', 'Decoration'),
        ('Electronics', 'Electronics'),
        ('Valuables', 'Valueables'),
        ('Other', 'Other'),
    ]
    STATUS = [
        ('Pending', 'Pending'),
        ('Closed', 'Closed'),
    ]
    DEFAULT_USER = 1
    name = models.CharField(max_length = 100, blank = False)
    initial = models.DecimalField(max_digits = 10, decimal_places = 2)
    user = models.ForeignKey(User, blank = False, on_delete = models.CASCADE, default = DEFAULT_USER)
    image = models.ImageField(default = 'None/NIA.png')
    category = models.CharField(max_length = 11, choices = CATEGORIES, default = 'Other')
    status = models.CharField(max_length = 7, choices = STATUS, default = 'Pending')
    created = models.DateField(auto_now_add = True)

    def __str__(self):
        return f"{self.name} - starts at ${self.initial}"

    
    def is_valid_listing(self):
        return len(self.name) > 0 and self.initial > 0

class Bid(models.Model):
    user = models.ForeignKey(User, blank = False, on_delete = models.CASCADE)
    listing = models.ForeignKey(Listing, blank = False, on_delete = models.CASCADE)
    highest_bid = models.DecimalField(max_digits = 10, decimal_places = 2)
    added = models.DateTimeField(auto_now = True)

    def __str__(self):
        return f"${self.highest_bid} - {self.user} on {self.listing.name}"


class Comment(models.Model):
    user = models.ForeignKey(User, blank = False, on_delete = models.CASCADE)
    listing = models.ForeignKey(Listing, blank = False, on_delete = models.CASCADE)
    comment = models.CharField(max_length = 400, blank = False)
    added = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return f"{self.comment} - by {self.user}"

auctions/forms.py
from django.forms import ModelForm
from .models import Listing

class ListingForm(ModelForm):
    class Meta:
        model = Listing
        fields = ['name', 'initial', 'image', 'category']

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages

from decimal import *

from .models import User, Listing, Bid, Comment
from .forms import ListingForm
from .decorators import Unauthenticated_user, Authenticated_user

watch_list = dict()

def index(request):
    listings = []
    items = Listing.objects.filter(status="Pending")
    for item in items:
        try:
            bid = Bid.objects.get(listing=item)
        except:
            bid = None
        listings.append({
            'listing': item,
            'bid': bid,
        })
    context = {
        'listings': listings,
    }
    return render(request, "auctions/index.html", context)

@Unauthenticated_user
def login_view(request):
    if request.method == "POST":


        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


@Authenticated_user
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


@Unauthenticated_user
def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html")

@Authenticated_user
def listing(request, listing):
    item = Listing.objects.get(pk=listing)
    old_bid = Bid.objects.filter(listing=item)
    if item.status == 'Closed':
        try:
            bid = old_bid[0]
            if bid.user == request.user:
                context = {
                    'listing': item,
                    'bid': bid,
                }
                return render(request, 'auctions/success.html', context)
        except:
            return render(request, 'auctions/closed.html')
        return render(request, 'auctions/closed.html') 
    comments = Comment.objects.filter(listing=item)
    if old_bid.count() is 1:
        default_bid = old_bid[0].highest_bid + 10
    else:
        default_bid = item.initial + 10
    try:
        bid_info = Bid.objects.get(listing=item)
    except:
        bid_info = None;
    context = {
        'listing': item,
        'bid': bid_info,
        'comments': comments,
        'default_bid': default_bid,
    }
    return render(request, "auctions/listing.html", context)

@Authenticated_user
def bid(request):
    if request.method == "POST":
        new_bid = request.POST["bid"]
        item_id = request.POST["list_id"]

        item = Listing.objects.get(pk=item_id)
        old_bid = Bid.objects.filter(listing=item)

        if old_bid.count() < 1:
            bid = Bid(user=request.user, listing=item, highest_bid=new_bid)
            bid.save()
            messages.success(request, 'Bid Placed Successfully!', fail_silently=True)
        elif Decimal(new_bid) < old_bid[0].highest_bid:
            messages.warning(request, 'The bid you placed was lower than needed.', fail_silently=True)
        elif Decimal(new_bid) == old_bid[0].highest_bid:
            messages.warning(request, 'The bid you placed was the same as the current bid', fail_silently=True)
        else:
            old_bid = Bid.objects.get(listing=item)
            old_bid.highest_bid = new_bid
            old_bid.user = request.user
            old_bid.save()
            messages.success(request, 'Bid Placed Successfully!', fail_silently=True)
    return redirect("auctions:listing", item_id)

@Authenticated_user
def comment(request):
    if request.method == "POST":
        content = request.POST["content"]
        item_id = request.POST["list_id"]
        item = Listing.objects.get(pk=item_id)
        newComment = Comment(user=request.user, comment=content, listing=item)
        newComment.save()
        return redirect("auctions:listing", item_id)
    return redirect("auctions:index")

@Authenticated_user
def watchlist(request):
    if request.user not in watch_list or watch_list[request.user] == []:
        context = {
            'message': "Nothing in your watchlist",
        }
        return render(request, "auctions/watchlist.html", context)
    listings = []
    for item_id in watch_list[request.user]:
        item = Listing.objects.get(pk=item_id)
        try:
            bid = Bid.objects.get(listing=item)
        except:
            bid = None
        listings.append({
            'listing': item,
            'bid': bid,
        })
    context = {
        'listings': listings,
    }
    return render(request, "auctions/watchlist.html", context)

@Authenticated_user
def add_to_watchlist(request, item_id):
    if request.user not in watch_list:
        watch_list[request.user] = []
        watch_list[request.user].append(item_id)
        messages.success(request, 'Successfully added item to your WatchList.', fail_silently=True)
    elif item_id in watch_list[request.user]:
        messages.warning(request, 'Item already present in your WatchList.', fail_silently=True)
    else:
        watch_list[request.user].append(item_id)
        messages.success(request, 'Successfully added item to your WatchList.', fail_silently=True)
    return redirect("auctions:index")

@Authenticated_user
def remove_from(request, item_id):
    if request.user not in watch_list:
        messages.warning(request, 'Cannot remove from empty WatchList.', fail_silently=True)
    elif item_id in watch_list[request.user]:
        watch_list[request.user].remove(item_id)
        messages.success(request, 'Successfully removed item from your WatchList.', fail_silently=True)
    else:
        messages.warning(request, 'Item not in your WatchList.', fail_silently=True)
    return redirect("auctions:index")

def categories(request):
    category = dict()
    listings = Listing.objects.filter(status="Pending")
    for item in listings:
        try:
            bid = Bid.objects.get(listing=item)
        except:
            bid = None
        if item.category not in category:
            category[item.category] = []
        category[item.category].append({
            'listing': item,
            'bid': bid,
        })
    context = {
        'category_list': category,
    }
    return render(request, "auctions/category.html", context)

@Authenticated_user
def success(request):
    return render(request, "auctions/success.html")

@Authenticated_user
def addListing(request):
    if request.method == "POST":
        form = ListingForm(request.POST, request.FILES or None)

        if form.is_valid():
            newListing = form.save(commit=False)
            newListing.user = request.user
            newListing.save()
            messages.success(request, 'Successfully created your listing.', fail_silently=True)
        else:
            messages.error(request, 'Invalid Listing!', fail_silently=True)
            return redirect("auctions:add_listing")
        return redirect("auctions:index")
    form = ListingForm()
    context = {
        'form': form,
    }
    return render(request, "auctions/addListing.html", context)

@Authenticated_user
def user_listings(request):
    listings = []
    current_user_listings = Listing.objects.filter(user=request.user, status='Pending')
    for item in current_user_listings:
        try:
            bid = Bid.objects.get(listing=item)
        except:
            bid = None
        listings.append({
            'listing': item,
            'bid': bid,
        })
    context = {
        'listings': listings,
    }
    return render(request, "auctions/userlistings.html", context)

@Authenticated_user
def close_listing(request, listing_id):
    listing = Listing.objects.get(pk=listing_id)
    if listing.user == request.user:
        listing.status = 'Closed'
        listing.save()
        messages.success(request, 'Listing successfully closed.', fail_silently=True)
    else:
        messages.warning(request, 'Unable to close listing! Authentication error.', fail_silently=True)
    return redirect("auctions:user_listings")

auctions/templates/auctions/addListing.html
{% extends "auctions/layout.html" %}

{% block body %}

<h2 class="blue-text">Add New Listing</h2>

  {% if messages %}
    {% for message in messages %}
    <div class="alert alert-danger">
      {{ message }}
    </div>
    {% endfor %}
  {% endif %}

  <form action="{% url 'auctions:add_listing' %}" class="login-form listing-form" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-primary" type="submit">Add Listing</button>
  </form>

{% endblock %}

auctions/templates/auctions/category.html
{% extends "auctions/layout.html" %}

{% block body %}
  <h2 class="blue-text">Categories</h2>

  {% if category_list %}
    <ul class="category-list bg-light">
    {% for key, category in category_list.items %}
      <li>
        <a class="btn btn-warning" href="#{{ key }}">{{ key }}</a>
      </li>
    {% endfor %}
    </ul>
    <hr>
    {% for key, category in category_list.items %}
      <ul class="listings">
        <h3 class="blue-text category-title" id="{{ key }}">{{ key }}</h3>
        {% for list in category %}
          <li>
            <div class="card">
              <div class="card-header">
                {{ list.listing.name }}
                {% if user.is_authenticated %}
                  {% ifequal list.listing.user user %}
                  <div class="owned-icon" title="You Own This Listing">
                    ★
                  </div>
                  {% endifequal %}
                {% endif %}
              </div>
              <div class="card-body">
                <img alt="{{ list.listing.name }} - img" src="{{ list.listing.image.url }}" height="170" />
                {% ifnotequal list.bid None %}
                <h5 class="list-cost" style="color: var(--danger)">Bidding has started on this item</h5>
                <h5 class="list-cost">Current Highest Bid: <strong style="color: var(--warning)">${{ list.bid.highest_bid }}</strong></h5>
                {% else %}
                <h5 class="list-cost" style="color: var(--success)">No Bids Currently Placed</h5>
                <h5 class="list-cost">Bid Starts From: <strong>${{ list.listing.initial }}</strong> </h5>
                {% endifnotequal %}
                {% if user.is_authenticated %}
                <div class="links-box">
                  <a class="btn btn-outline-primary" href="{% url 'auctions:listing' list.listing.id %}">View Listing</a>
                  <a class="btn btn-outline-success" href="{% url 'auctions:add_to' list.listing.id %}">Add to WatchList</a>
                  {% ifequal list.listing.user user %}
                  <a class="btn btn-outline-danger" href="{% url 'auctions:close_listing' list.listing.id %}">Close Listing</a>
                  {% endifequal %}
                </div>
                {% else %}
                <a class="nav-link" href="{% url 'auctions:login' %}">LogIn to view listing</a>
                {% endif %}
                <h6 class="text-muted right-align">Date added: {{ list.listing.created }}</h6>
              </div>
            </div>
          </li>
        {% endfor %}
      </ul>
      <hr>
    {% endfor %}
  {% endif %}

{% endblock %}

auctions/templates/auctions/closed.html
{% extends "auctions/layout.html" %}

{% block title %}
Success
{% endblock %}

{% block body %}

<div class="card border-danger success-card" style="color: var(--danger);">
  <h4 class="card-header border-danger bg-light">Sorry!</h4>
  <div class="card-body">
    Ths listing you are looking for has been closed by its owner.
  </div>
</div>

{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
  <div class="add-listing-container">
    <h2 class="blue-text margin-bot">
      Active Listings
    </h2>
    {% if user.is_authenticated %}
    <h5 title="add listing" class="plus-container">
      <a class="btn btn-outline-success plus-link" href="{% url 'auctions:add_listing' %}">+ Add new Listing</a>
      <a class="btn btn-outline-warning plus-link" href="{% url 'auctions:user_listings' %}">
        View Your Listings
      </a>
    </h5>
    {% endif %}
  </div>

  {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
      {{ message }}
    </div>
    {% endfor %}
  {% endif %}

  {% if listings %}
  <ul class="listings">
    {% for list in listings %}
    <li>
      <div class="card">
        <div class="card-header">
          {{ list.listing.name }}
          {% ifequal list.listing.user user %}
          <div class="owned-icon" title="You Own This Listing">
            ★
          </div>
          {% endifequal %}
        </div>
        <div class="card-body">
          <img alt="{{ list.listing.name }} - img" src="{{ list.listing.image.url }}" height="170" />
          {% ifnotequal list.bid None %}
          <h5 class="list-cost" style="color: var(--danger)">Bidding has started on this item</h5>
          <h5 class="list-cost">Current Highest Bid: <strong style="color: var(--warning)">${{ list.bid.highest_bid }}</strong></h5>
          {% else %}
          <h5 class="list-cost" style="color: var(--success)">No Bids Currently Placed</h5>
          <h5 class="list-cost">Bid Starts From: <strong>${{ list.listing.initial }}</strong> </h5>
          {% endifnotequal %}
          <h5> Category: <strong style="color: var(--gray)">{{ list.listing.category }}</strong> </h5>
          {% if user.is_authenticated %}
          <div class="links-box">
            <a class="btn btn-outline-primary" href="{% url 'auctions:listing' list.listing.id %}">View Listing</a>
            <a class="btn btn-outline-success" href="{% url 'auctions:add_to' list.listing.id %}">Add to WatchList</a>
            {% ifequal listing.user user %}
            <a class="btn btn-outline-danger" href="{% url 'auctions:close_listing' list.listing.id %}">Close Listing</a>
            {% endifequal %}
          </div>
          {% else %}
          <a class="nav-link" href="{% url 'auctions:login' %}">LogIn to view listing</a>
          {% endif %}
          <h6 class="text-muted right-align">Date added: {{ list.listing.created }}</h6>
        </div>
      </div>
    </li>
    {% endfor %}
    <li class="card card-header bg-info">
      <div style="text-align: center; color: white;"> --- END --- </div>
    </li>
  </ul>
  {% endif %}
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %}THEBAZAAR{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
  </head>
  <body>
    <h1 id="auction-title">THEBAZAAR</h1>
    <nav>
      {% if user.is_authenticated %}
      <div class="username">
        Signed in as <strong style="color: var(--indigo)">{{ user.username }}</strong>.
      </div>
      {% endif %}
      <ul class="nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'auctions:categories' %}">Categories</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'auctions:watchlist' %}">WatchList</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
        </li>
        {% endif %}
      </ul>
    </nav>
    <br>
    <hr>
    {% block body %}
    {% endblock %}
  </body>
</html>

auctions/templates/auctions/listing.html
{% extends "auctions/layout.html" %}

{% block title %}
{{ listing.name }}
{% endblock %}

{% block body %}

{% if messages %}
  {% for message in messages %}
  <div class="alert alert-{{ message.tags }}">
    {{ message }}
  </div>
  {% endfor %}
{% endif %}

<h2 class="listing-name">{{ listing.name }}</h2>

<div class="listing-img" >
  <img alt="{{ listing.name }} - img" src="{{ listing.image.url }}" />
</div>

<div class="bid-info">
  {% if bid %}
  Current Highest Bid: <strong style="color: var(--danger)">${{ bid.highest_bid }}</strong>
  <br>
  By: <span style="color: var(--warning)">{{ bid.user }}</span>
  <div class="text-muted">Bid added at {{ bid.added }}</div>
  <br><br>
  {% else %}
  <span style="color: var(--success)">
    No Bids Currently Placed
  </span>
  <br>
  Bids start from <strong style="color: var(--warning)">${{ listing.initial }}</strong>
  <br><br>
  {% endif %}
  <a class="btn btn-success" href="{% url 'auctions:add_to' listing.id %}">Add to WatchList</a>
  {% ifequal listing.user user %}
  <br><br>
  <a class="btn btn-danger" href="{% url 'auctions:close_listing' listing.id %}">Close Listing</a>
  {% endifequal %}
</div>
<hr>
{% ifnotequal listing.user user %}
<h5>Bid </h5>
<form class="login-form" action="{% url 'auctions:bid' %}" method="POST">
  {% csrf_token %}
  <div class="input-group">
    <div class="input-group-prepend">
      <div class="input-group-text bg-warning">$</div>
    </div>
    <input class="form-control" type="number" min="1" name="bid" value="{{ default_bid }}" placeholder="Enter your bid here">
  </div>
  <input name="list_id" type="hidden" value="{{ listing.id }}" />
  <button class="btn btn-primary" type="submit" style="margin-top: 10px;">Place Bid</button>
</form>
{% else %}
<div class="alert alert-info">
  Owner cannot bid on their own item.
</div>
{% endifnotequal %}
<hr>
<div class="listing-comments">
  <h5>Comments </h5>
  <div class="comment-container">
  {% if comments %}
    {% for comment in comments %}
    <div class="card bg-light border-success" style="margin: 5px;">
      <div class="comment-owner">
        {{ comment.user }}
      </div>
      <span class="comment-content">
        {{ comment.comment }}
      </span>
      <span class="text-muted" style="text-align: right; margin-right: 5px;">
        {{ comment.added }}
      </span>
    </div>
    {% endfor %}
  {% else %}
  <span class="text-muted">
    No comments at the moment
  </span>
  {% endif %}
  </div>
  <hr>
  <form class="comment-form" action="{% url 'auctions:comment' %}" method="POST">
    Your Comment:
    {% csrf_token %}
    <textarea name="content" class="form-control" placeholder="enter your comment here" rows="3" maxlength="400"></textarea>
    <input name="list_id" type="hidden" value="{{ listing.id }}" />
    <button class="btn btn-primary" type="submit">Comment</button>
  </form>
</div>

{% endblock %}

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2 class="blue-text">Login</h2>

    {% if message %}
        <div class="alert alert-danger">{{ message }}</div>
    {% endif %}

    <form class="login-form" action="{% url 'auctions:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    <div class="center-text">
      Don't have an account? <a href="{% url 'auctions:register' %}">Register here.</a>
    </div>

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2 class="blue-text">Register</h2>

    {% if message %}
        <div class="alert alert-danger">{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:register' %}" method="post" class="register-form login-form">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    <div class="center-text">
      Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a>
    </div>

{% endblock %}

auctions/templates/auctions/success.html
{% extends "auctions/layout.html" %}

{% block title %}
Success
{% endblock %}

{% block body %}

<div class="card border-success success-card">
  <h4 class="card-header border-success bg-light">Success {{ request.user }}!</h4>
  <div class="card-body">
    <img src="{{ listing.image.url }}" alt="{{ listing.name }}" height="200" />
    <br>
    You have successfully won the bid for: <strong style="color: var(--gray)">{{ listing.name }}</strong>
    <br>
    For the price of: <strong style="color: var(--warning)">${{ bid.highest_bid }}</strong>
  </div>
</div>

{% endblock %}

auctions/templates/auctions/userlistings.html
{% extends "auctions/layout.html" %}

{% block body %}

  <h2 class="blue-text">Your Listings</h2>
  <h5 title="add listing" class="plus-container">
    <a class="btn btn-outline-success plus-link" href="{% url 'auctions:add_listing' %}">+ Add new Listing</a>
  </h5>

  {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
      {{ message }}
    </div>
    {% endfor %}
  {% endif %}

  {% if listings %}
  <ul class="listings">
    {% for list in listings %}
    <li>
      <div class="card">
        <div class="card-header">
          {{ list.listing.name }}
          {% ifequal list.listing.user user %}
          <div class="owned-icon" title="You Own This Listing">
            ★
          </div>
          {% endifequal %}
        </div>
        <div class="card-body">
          <img alt="{{ list.listing.name }} - img" src="{{ list.listing.image.url }}" height="170" />
          {% ifnotequal list.bid None %}
          <h5 class="list-cost" style="color: var(--danger)">Bidding has started on this item</h5>
          <h5 class="list-cost">Current Highest Bid: <strong style="color: var(--warning)">${{ list.bid.highest_bid }}</strong></h5>
          {% else %}
          <h5 class="list-cost" style="color: var(--success)">No Bids Currently Placed</h5>
          <h5 class="list-cost">Bid Starts From: <strong>${{ list.listing.initial }}</strong> </h5>
          {% endifnotequal %}
          <h5> Category: <strong style="color: var(--gray)">{{ list.listing.category }}</strong> </h5>
          <div class="links-box">
            <a class="btn btn-outline-primary" href="{% url 'auctions:listing' list.listing.id %}">View Listing</a>
            <a class="btn btn-outline-success" href="{% url 'auctions:add_to' list.listing.id %}">Add to WatchList</a>
            {% ifequal list.listing.user user %}
            <a class="btn btn-outline-danger" href="{% url 'auctions:close_listing' list.listing.id %}">Close Listing</a>
            {% endifequal %}
          </div>
          <h6 class="text-muted right-align">Date added: {{ list.listing.created }}</h6>
        </div>
      </div>
    </li>
    {% endfor %}
    <li class="card card-header bg-info">
      <div style="text-align: center; color: white;"> --- END --- </div>
    </li>
  </ul>
  {% else %}
  <div class="alert alert-info">
    You don't currently possess any active listings.
  </div>
  {% endif %}

{% endblock %}

auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}

{% block body %}
  <h2 class="blue-text">WatchList</h2>

  {% if message %}
  <div class="alert alert-info">
    {{ message }}
  </div>
  {% endif %}

  {% if listings %}
  <ul class="listings">
    {% for list in listings %}
    <li>
      <div class="card">
        <div class="card-header">
          {{ list.listing.name }}
        </div>
        <div class="card-body">
          <img alt="{{ list.listing.name }} - img" src="{{ list.listing.image.url }}" height="170" />
          {% ifnotequal list.bid None %}
          <h5 class="list-cost" style="color: var(--danger)">Bidding has started on this item</h5>
          <h5 class="list-cost">Current Highest Bid: <strong style="color: var(--warning)">${{ list.bid.highest_bid }}</strong></h5>
          {% else %}
          <h5 class="list-cost" style="color: var(--success)">No Bids Currently Placed</h5>
          <h5 class="list-cost">Bid Starts From: <strong>${{ list.listing.initial }}</strong> </h5>
          {% endifnotequal %}
          <div class="links-box">
            <a class="btn btn-outline-primary" href="{% url 'auctions:listing' list.listing.id %}">View Listing</a>
            <a class="btn btn-outline-success" href="{% url 'auctions:add_to' list.listing.id %}">Add to WatchList</a>
          </div>
          <br> <br>
          <a class="btn btn-outline-danger" href="{% url 'auctions:remove' list.listing.id %}">Remove from WatchList</a>
          <h6 class="text-muted right-align">Date added: {{ list.listing.created }}</h6>
        </div>
      </div>
    </li>
    {% endfor %}
    <li class="card card-header bg-info">
      <div style="text-align: center; color: white;"> --- END --- </div>
    </li>
  </ul>
  {% endif %}

{% endblock %}